id: P008175
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG25572
  title: ཁྲི་འདུས་སྲོང་གི་མགུར་གླུར་དཔྱད་པ།
  author: ''
  volumes:
    a6bfd3edf99e4f7ea0fe7ad55333ee0a:
      image_group_id: I1KG25574
      title: ''
      volume_number: 1
      total_pages: 266
      base_file: v001.txt
